### ISSUE TITLE
Input doesn't work properly

### ISSUE THREAD

**Issue by nathannieuwenhuizen** [kmopman/Travelling#4]
The clientofset gets probably calculated too:

`private inputDown(pointer: Phaser.Pointer): void
    {
        this.onInputDown.dispatch(Lanes.Conversions.screenPositionToLane(this.game, pointer.clientX, pointer.clientY));
    }
`

**Comment by DavidZwitser** [comment]
https://github.com/kmopman/Travelling/commit/61dde6a00ff81fbd422065507d14fc9ed0dd3a51
Fixed it!
